# Generated by Django 2.2 on 2020-12-21 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nextapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='re_me',
            old_name='group',
            new_name='group_ph',
        ),
    ]
