# Generated by Django 2.2 on 2020-12-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextapp', '0002_auto_20201221_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='re_me',
            name='group_ph',
            field=models.FileField(upload_to='images/'),
        ),
    ]
